<?php

/**
 * @file
 * Contains sg_entity_services.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sg_entity_services_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sg_entity_services module.
    case 'help.page.sg_entity_services':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Entity Services module.') . '</p>';
      return $output;

    default:
  }
}
